version: '3.3'

services:
  phpapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    image: php:8.2-apache
    env_file:
      - .env
    ports:
      - 8181:80
    volumes:
      - ./php:/var/www/html

  bd:
    image: mysql
    container_name: bd
    env_file:
      - .env
    ports:
      - 20762:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - bd

networks:
  lan:
    external: false
